// GENERATED by build/gen-version.mjs from package.json -- do not edit.
// Run `fyn run gen-version` (or any build) to refresh.

/** The version of `@fynmesh/kernel` this build was produced from. */
export const KERNEL_VERSION = "1.1.2";
